version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test-ci
          environment:
            JUNIT_REPORT_PATH: ./junit/
            JUNIT_REPORT_NAME: test-results.xml
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
      - persist_to_workspace:
          root: ~/
          paths:
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/node:10-browsers
    steps:
      - attach_workspace:
            at: ~/
      - run:
          command: npm install ionic
      - run:
          command: ./node_modules/.bin/ionic build --prod --service-worker
      - run:
          command: npm install --save-dev firebase-tools
      - run:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --project $FIREBASE_PROJECT_ID
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "20 5 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
