name: deploy to production

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npx ionic build --prod
      - uses: actions/upload-artifact@master
        with:
         name: www
         path: www
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@master
        with:
          name: www
          path: www
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.7.3
        with:
          args: deploy --only hosting -P funfunspell-firebase
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FUNFUNSPELL_FIREBASE }}
